### ISSUE TITLE
Look into two-stage build

### ISSUE THREAD

**Issue by jeffyjefflabs** [nbgallery/docker-images#11]
Installing Lab extensions splatters stuff all over the file system... `/tmp`, yarn caches, etc.  Two-stage build simplifies cleanup.

Related issues:
 * https://github.com/jupyterlab/jupyterlab/issues/4930
 * https://github.com/jupyter/docker-stacks/issues/752

**Comment by mcrutch** [comment]
With pre-compiled extensions we don't have all the yarn caches and all that garbage anymore, so just closing this ticket.
