### ISSUE TITLE
default notebook dir should be `/home/jovyan` not `/home/jovyan/notebooks`

### ISSUE THREAD

**Issue by kafonek** [nbgallery/docker-images#13]
I want to say using `~/notebooks` was a decision made when the Alpine-based flask was being used, then kept for backwards compatibility.  We should consider changing the default `notebook_dir` to be `/home/jovyan` to match `jupyter/base-notebook` behavior.  Also, the terminal window opens to `/home/jovyan` not `/home/jovyan/notebooks` and that is confusing/annoying to many users.  

The risks are that some Notebooks already written expect to be in the `/home/jovyan/notebooks` directory and are using absolute paths that will break if the directory is changed.  I think that clearing up confusion is worth the impact to those Notebooks.

**Comment by jeffyjefflabs** [comment]
The challenge is we want the notebook directory to be able to be mounted in via docker so notebooks can persist outside the container.  That gets a whole lot messier when that directory is a user home directory, given all the config files that need to be there plus things that get dropped there during runtime.  Of particular concern is that if `/home/jovyan` is mounted in and you restart the container, then local pip-installed packages can end up out of sync with Linux packages installed via ipydeps configuration.

Partial workaround maybe we have a bashrc that changes directory to where the notebooks are?  That would at least resolve the terminal inconsistency.

**Comment by cccs-cat001** [comment]
Any chance the default dir could be configurable? We'd rather have it be /home/jovyan instead of /home/jovyan/notebooks, as the /home/jovyan/notebooks will be saved in our /home/jovyan volume.

**Comment by jeffyjefflabs** [comment]
Yeah, that's probably doable - off the top of my head, setting it via environment variable probably makes the most sense but don't quote me on that yet.

**Comment by jeffyjefflabs** [comment]
You'll be able to set `$NOTEBOOK_DIR` in the next release (1.1.5) - either via `-e` on the `docker run` command line or in the Dockerfile if you're using our image as a base.

**Comment by jeffyjefflabs** [comment]
(But the default is still `/home/jovyan/notebooks`)
