### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by haha150** [nbgallery/docker-images#7]
How are you able to use the base-notebook with nbgallery?

I have built the image and have nbgallery running.

**Comment by jeffyjefflabs** [comment]
Sorry for the confusion - this repo is a work in progress and the READMEs are a little ahead of the code.  We're in the middle of refactoring the nbgallery integration scripts, so at the moment this image doesn't have nbgallery integration yet.  For now, you could try our [old image](https://github.com/nbgallery/jupyter-alpine) (still works, but old versions of various things, including Jupyter itself).  We're hoping to have this image ready in the next few weeks.

**Comment by haha150** [comment]
Aha, yes i see, i was actually using the old image that you linked and wanted to try this one. Thanks!

**Comment by haha150** [comment]
Hi, is there any ETA on the base image release?

**Comment by jeffyjefflabs** [comment]
Coincidentally I was working on that today!  I finished the refactor of [our extensions](https://github.com/nbgallery/nbgallery-extensions) and I just pushed a new version of the image (nbgallery/base-notebook) to docker hub. I still have a few things to add (notably, the environment variables mentioned [here](https://github.com/nbgallery/nbgallery/blob/master/docs/jupyter_integration.md#optional-integration-scripts)), but the basics are there and it should work fine with nbgallery now.  Note that default entrypoint on this image is non-secure http on port 8888, as opposed to https 443 in the old one.  Let us know if you see any problems!

**Comment by jeffyjefflabs** [comment]
I would suggest doing any conda installs as jovyan user and see if that makes a difference.  Jupyter itself should be running as jovyan (the container starts as root but then switches to jovyan to run jupyter).  The jovyan user has sudo so you can still do apt installs too.

**Comment by haha150** [comment]
Yeah, i am actually not able to install javacsript kernel at all in any way (conda or apt) with root or jovyan.
